runtime: python37

entrypoint: gunicorn -b :$PORT flask_app:ipl_app

handlers:
  - url: /static
    static_dir: flask_app/static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'google-cloud.json'